variable "instance_name" {
  description = "This is a Gitlab EC2 instance"
  type        = string
  default     = "GitlabServerInstance"
}
variable "vpc_id" {
  description = "vpc-id"
  type        = string
  default     = "vpc-05d66555d35008729"
}
variable "generated_key_name" {
  type        = string
  default     = "GitlabServerKey"
  description = "Key-pair generated by Terraform for Gitlab"
}
variable "gitlab_runer_generated_key_name" {
  type        = string
  default     = "GitlabRunnerKey"
  description = "Key-pair generated by Terraform for Gitlab runner"
}

variable "rds_port" {
  type    = number
  default = 5432
}

variable "ip_address" {
  default = ["192.168.128.0/24", "154.160.75.86/32", "102.176.73.186/32", "192.168.10.0/24"]
}

variable "ownerTag" {
  default = "DevOps"
}