variable "instance_name" {
  description = "This is a Gitlab EC2 instance"
  type        = string
  default     = "GitlabServerInstance"
}

variable "generated_key_name" {
  type        = string
  default     = "GitlabServerKey"
  description = "Key-pair generated by Terraform for Gitlab"
}

variable "rds_port" {
  type    = number
  default = 5432
}



variable "ip_address" {
  default = ["192.168.128.0/24","154.160.75.86/32","102.176.73.186/32","192.168.10.0/24"]
}

variable "ownerTag" {
  default = "DevOps"
}